#define CONFIG_CCSECURITY_MAX_AUDIT_LOG    1024
#define CONFIG_CCSECURITY_MAX_ACCEPT_ENTRY 2048
//#define CONFIG_CCSECURITY_OMIT_USERSPACE_LOADER
#define CONFIG_CCSECURITY_POLICY_LOADER "/sbin/ccs-init"
#define CONFIG_CCSECURITY_ACTIVATION_TRIGGER "/sbin/init"
//#define CONFIG_AKARI_DEBUG
//#define CONFIG_AKARI_TRACE_EXECVE_COUNT
#define CONFIG_CCSECURITY_FILE_READDIR
#define CONFIG_CCSECURITY_FILE_GETATTR
#ifdef CONFIG_SECURITY_NETWORK
#define CONFIG_CCSECURITY_NETWORK
#endif
#define CONFIG_CCSECURITY_MISC
#define CONFIG_CCSECURITY_TASK_EXECUTE_HANDLER
#define CONFIG_CCSECURITY_TASK_DOMAIN_TRANSITION
